AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM for deploying backend of my cloud resume challenge

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
    Architectures:
      - arm64
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref Database
  Api:
    TracingEnabled: true

Resources:
  Database:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: resume-visitors
      PrimaryKey:
        Name: visitors
        Type: String

  # Get All Visitors
  GetVisitorAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: apis/
      Handler: lambda_function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Database
      Events:
        Api:
          Type: Api
          Properties:
            Path: /visitors
            Method: get

Outputs:
  VisitorAPIEndPoints:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
